# Generated by Django 3.2.3 on 2022-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion', models.CharField(choices=[('Br', 'Bruise'), ('Cv', 'Cavity'), ('Ch', 'Chip'), ('Clv', 'Cleavage'), ('Cld', 'Cloud'), ('Xtl', 'Crystal'), ('Ftr', 'Feather'), ('GrCnt', 'Grain Center'), ('IndN', 'Indented Natural'), ('IntGr', 'Internal Graining'), ('K', 'Knot'), ('LDH', 'Laser Drill Hole'), ('Ndl', 'Needle'), ('Pp', 'Pinpoint'), ('W', 'Twinning Wisp'), ('Abr', 'Abrasion'), ('N', 'Natural'), ('Nk', 'Nick'), ('Pit', 'Pit'), ('PL', 'Polish Line'), ('BG', 'Bearded Girdle'), ('PM', 'Polish Mark'), ('RG', 'Rough Girdle'), ('S', 'Scratch'), ('SGr', 'Surface Graining'), ('EF', 'Extra Facet'), ('brn', 'Burn Marks'), ('EC', 'Etch Channels'), ('LMR', 'Laser Manufacturing Remnants')], max_length=5, unique=True)),
            ],
        ),
    ]
