# Generated by Django 3.1.7 on 2021-02-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inclusion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "inclusion",
                    models.CharField(
                        choices=[
                            ("Br", "Bruise"),
                            ("Cv", "Cavity"),
                            ("Ch", "Chip"),
                            ("Clv", "Cleavage"),
                            ("Cld", "Cloud"),
                            ("Xtl", "Xtl"),
                            ("Ftr", "Feather"),
                            ("GrCnt", "Grain Center"),
                            ("IndN", "Indented natural"),
                            ("IntGr", "Internal graining"),
                            ("K", "knot"),
                            ("LDH", "Laser Drill Hole"),
                            ("Ndl", "Needle"),
                            ("Pp", "Pinpoint"),
                            ("W", "Twinning Wisp"),
                            ("Abr", "Abrasion"),
                            ("N", "Natural"),
                            ("Nk", "Nick"),
                            ("Pit", "Pit"),
                            ("PL", "Polish Line"),
                            ("Brn", "Burn Mask"),
                            ("S", "Scratch"),
                            ("SGr", "Surface Graining"),
                            ("EF", "Extra Feet"),
                        ],
                        max_length=5,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
