# Generated by Django 3.2.3 on 2021-08-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonegrading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusion',
            name='inclusion',
            field=models.CharField(choices=[('Br', 'Bruise'), ('Cv', 'Cavity'), ('Ch', 'Chip'), ('Clv', 'Cleavage'), ('Cld', 'Cloud'), ('Xtl', 'Xtl'), ('Ftr', 'Feather'), ('GrCnt', 'Grain Center'), ('IndN', 'Indented natural'), ('IntGr', 'Internal graining'), ('K', 'knot'), ('LDH', 'Laser Drill Hole'), ('Ndl', 'Needle'), ('Pp', 'Pinpoint'), ('W', 'Twinning Wisp'), ('Abr', 'Abrasion'), ('N', 'Natural'), ('Nk', 'Nick'), ('Pit', 'Pit'), ('PL', 'Polish Line'), ('BG', 'Bearded Gridle'), ('PM', 'Polish Mark'), ('RG', 'Rough Girdle'), ('S', 'Scratch'), ('SGr', 'Surface Graining'), ('EF', 'Extra Facet')], max_length=5, unique=True),
        ),
    ]
