# Generated by Django 3.2.8 on 2021-10-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonegrading', '0004_alter_inclusion_inclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusion',
            name='inclusion',
            field=models.CharField(choices=[('Br', 'Bruise'), ('Cv', 'Cavity'), ('Ch', 'Chip'), ('Clv', 'Cleavage'), ('Cld', 'Cloud'), ('Xtl', 'Crystal'), ('Ftr', 'Feather'), ('GrCnt', 'Grain Center'), ('IndN', 'Indented Natural'), ('IntGr', 'Internal Graining'), ('K', 'Knot'), ('LDH', 'Laser Drill Hole'), ('Ndl', 'Needle'), ('Pp', 'Pinpoint'), ('W', 'Twinning Wisp'), ('Abr', 'Abrasion'), ('N', 'Natural'), ('Nk', 'Nick'), ('Pit', 'Pit'), ('PL', 'Polish Line'), ('BG', 'Bearded Girdle'), ('PM', 'Polish Mark'), ('RG', 'Rough Girdle'), ('S', 'Scratch'), ('SGr', 'Surface Graining'), ('EF', 'Extra Facet'), ('brn', 'Burn Marks'), ('EC', 'Etch Channels'), ('LMR', 'Laser Manufacturing Remnants')], max_length=5, unique=True),
        ),
    ]
